import { BoardGame, Cafe, User, Meetup, Tournament, Bill, Chat, MeepleAward } from './types';

// ---- Board Games ----
export const GAMES: BoardGame[] = [
  {
    id: 'g1', name: 'Codenames', difficulty: 'light', weight: 1.4,
    minPlayers: 2, maxPlayers: 8, playTimeMin: 30, teachTimeMin: 5,
    category: 'social-deduction',
    coverUrl: 'https://cdn.prod.website-files.com/67d17a45b4e1484b40ea8869/6836d01be6d1472eccb6fb20_web-box.webp',
    blurb: 'Two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their codenames. The spymasters take turns giving one-word clues.',
    cafeIds: ['c1', 'c2', 'c3', 'c4'],
  },
  {
    id: 'g2', name: 'Catan', difficulty: 'medium', weight: 2.3,
    minPlayers: 3, maxPlayers: 4, playTimeMin: 90, teachTimeMin: 20,
    category: 'strategy',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a3/Catan-2015-boxart.jpg',
    blurb: 'Settle the island of Catan! Trade resources, build roads, cities and settlements, and earn victory points. The first to 10 VP wins.',
    cafeIds: ['c1', 'c2', 'c3', 'c5'],
  },
  {
    id: 'g3', name: 'Wingspan', difficulty: 'medium', weight: 2.4,
    minPlayers: 1, maxPlayers: 5, playTimeMin: 70, teachTimeMin: 20,
    category: 'strategy',
    coverUrl: 'https://stonemaiergames.com/wp-content/uploads/2026/04/3d-wingspan-860x1024.webp',
    blurb: 'A competitive engine-building game about birds. Each bird extends a chain of powerful combinations in your habitat. Beautiful and strategic.',
    cafeIds: ['c2', 'c3', 'c4', 'c6'],
  },
  {
    id: 'g4', name: 'Pandemic', difficulty: 'medium', weight: 2.4,
    minPlayers: 2, maxPlayers: 4, playTimeMin: 60, teachTimeMin: 15,
    category: 'coop',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/36/Pandemic_game.jpg',
    blurb: 'Four diseases are spreading across the globe. Your team of specialists must work together to find cures before the outbreaks spiral out of control.',
    cafeIds: ['c1', 'c4', 'c5', 'c6'],
  },
  {
    id: 'g5', name: 'Ticket to Ride', difficulty: 'light', weight: 1.9,
    minPlayers: 2, maxPlayers: 5, playTimeMin: 60, teachTimeMin: 15,
    category: 'family',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/9/92/Ticket_to_Ride_Board_Game_Box_EN.jpg',
    blurb: 'Collect and play train cards to claim railway routes across a map. Build the longest routes and complete Destination Tickets for bonus points.',
    cafeIds: ['c1', 'c2', 'c5', 'c6'],
  },
  {
    id: 'g6', name: 'Brass: Birmingham', difficulty: 'heavy', weight: 3.9,
    minPlayers: 2, maxPlayers: 4, playTimeMin: 120, teachTimeMin: 45,
    category: 'strategy',
    coverUrl: 'https://cdn.shopify.com/s/files/1/0246/2190/8043/t/5/assets/f78ba2a93e5e--BrassB-RetailBoxImage.png',
    blurb: 'An economic strategy game set in the industrial revolution. Build canals and rails, develop industries, and ship goods across the Midlands.',
    cafeIds: ['c3', 'c4', 'c6'],
  },
  {
    id: 'g7', name: 'Twilight Imperium', difficulty: 'heavy', weight: 4.3,
    minPlayers: 3, maxPlayers: 6, playTimeMin: 360, teachTimeMin: 60,
    category: 'strategy',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/en/7/77/Twilight-imperium-layout_12.jpg',
    blurb: 'An epic game of galactic conquest, politics, and trade. Each player commands a unique alien civilization vying for control of the galaxy.',
    cafeIds: ['c4', 'c6'],
  },
  {
    id: 'g8', name: 'Coup', difficulty: 'light', weight: 1.4,
    minPlayers: 2, maxPlayers: 6, playTimeMin: 20, teachTimeMin: 5,
    category: 'social-deduction',
    coverUrl: 'https://www.ultraboardgames.com/img/slideshow/coup.jpg',
    blurb: 'In a dystopian future, the government is run by a small group of corrupt officials. Lie, bluff, and backstab your way to power. Eliminate every rival.',
    cafeIds: ['c1', 'c2', 'c3', 'c4', 'c5', 'c6'],
  },
];

export const GAME_MAP: Record<string, BoardGame> = Object.fromEntries(GAMES.map(g => [g.id, g]));

// ---- Cafes — real Chennai board game venues ----
export const CAFES: Cafe[] = [
  {
    id: 'c1', name: 'The Board Room Café', area: 'Mylapore', city: 'Chennai',
    photos: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiXz95ur2Lpxe4pkpWWtN5miJuBHjO2mWChC3zYWNrG4hov8Rxxt9J-CVdOKbAVSKWES61EygiLEYxzgQcnrt8b6Fp9eaVCLdOO6Lanq3Jj8fG4_pw6qJj8UWzdygevR7Q1Av6AHA/s1600/the+board+room+cafe.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxBzw6bRV5uStK46R_EKqltzBXVdBOfwS8H_rxnDfOMB-mLrSIu0WDhP11rb8p8ONCpGDlB17qa5js2p2M0AQmSm8nbGykT4p39MNmxiMfpzEFiQ9hyzrAB-F8qhGcQA/s1600/lots+of+board+games.jpg',
    ],
    rating: 4.5,
    reviews: [
      { id: 'r1', author: 'Arun M.', stars: 5, date: '2025-11-20', text: 'Open Table Thursdays are brilliant. The staff helped our group pick Catan and we were hooked for three hours. Excellent collection and great vibes.' },
      { id: 'r2', author: 'Priya S.', stars: 4, date: '2025-11-15', text: 'Heavy-Weight Wednesdays introducing Euro games was a great concept. Cosy space and the weekday pricing is very reasonable.' },
      { id: 'r3', author: 'Karthik R.', stars: 5, date: '2025-10-30', text: 'Their Catan Summer Slam was incredibly well organised. Staff are enthusiasts who genuinely love helping new players.' },
    ],
    pricePerHour: 120, perPerson: true,
    tables: [
      { id: 't1-1', label: 'Table 1', seats: 6 },
      { id: 't1-2', label: 'Table 2', seats: 4 },
      { id: 't1-3', label: 'Table 3', seats: 8 },
      { id: 't1-4', label: 'Table 4', seats: 4 },
    ],
    gameLibraryIds: ['g1', 'g2', 'g4', 'g5', 'g8'],
    amenities: ['AC', 'Food & Drinks', 'Wi-Fi', 'Washrooms'],
    offer: { text: 'Weekday entry ₹120, weekend ₹180 per person', window: 'Mon–Sun, 11 am – 10 pm' },
    distanceKm: 4.5, hours: '11 am – 10 pm', lat: 13.0339, lng: 80.2619,
  },
  {
    id: 'c2', name: 'GameOn Café', area: 'T. Nagar', city: 'Chennai',
    photos: [
      'https://thesouthfirst.com/wp-content/uploads/2023/08/game-on-4.jpg',
    ],
    rating: 4.2,
    reviews: [
      { id: 'r4', author: 'Deepa K.', stars: 4, date: '2025-11-10', text: 'Cosy spot right in T. Nagar. Staff are friendly and the game collection covers all the classics. Wingspan copy here is pristine.' },
      { id: 'r5', author: 'Vikram L.', stars: 5, date: '2025-10-25', text: 'Hosted my first meetup here and the staff set everything up perfectly. Reasonable weekday pricing.' },
    ],
    pricePerHour: 99, perPerson: true,
    tables: [
      { id: 't2-1', label: 'Table 1', seats: 5 },
      { id: 't2-2', label: 'Table 2', seats: 4 },
      { id: 't2-3', label: 'Table 3', seats: 6 },
    ],
    gameLibraryIds: ['g1', 'g2', 'g3', 'g5', 'g8'],
    amenities: ['AC', 'Food & Drinks', 'Wi-Fi', 'Washrooms'],
    distanceKm: 3.2, hours: '11 am – 10 pm', lat: 13.0358, lng: 80.2327,
  },
  {
    id: 'c3', name: 'The Board Game Lounge', area: 'Adyar', city: 'Chennai',
    photos: [
      'https://thesouthfirst.com/wp-content/uploads/2023/08/BOARDGAME-lounge-1.jpg',
      'https://imgmediagumlet.lbb.in/media/2019/03/5c8fada1ce22e545ca2955bc_1552919969786.jpg',
    ],
    rating: 4.4,
    reviews: [
      { id: 'r6', author: 'Meera T.', stars: 5, date: '2025-11-18', text: 'Love that they have games based on books and anime. Codenames + Coup back to back was the perfect evening. Very knowledgeable staff.' },
      { id: 'r7', author: 'Ravi P.', stars: 4, date: '2025-11-05', text: 'Flat ₹300 entry is fair given the experience. The Brass: Birmingham table was free on a Saturday — that\'s rare.' },
    ],
    pricePerHour: 300, perPerson: true,
    tables: [
      { id: 't3-1', label: 'Table 1', seats: 4 },
      { id: 't3-2', label: 'Table 2', seats: 6 },
      { id: 't3-3', label: 'Table 3', seats: 8 },
      { id: 't3-4', label: 'Table 4', seats: 4 },
      { id: 't3-5', label: 'Table 5', seats: 6 },
    ],
    gameLibraryIds: ['g1', 'g2', 'g4', 'g6', 'g8'],
    amenities: ['AC', 'Food & Drinks', 'Washrooms'],
    distanceKm: 8.1, hours: '2 pm – 10 pm (Tue–Fri), 12 pm – 9 pm (Sat–Sun)', lat: 13.0012, lng: 80.2565,
  },
  {
    id: 'c4', name: 'Gameistry', area: 'Egmore', city: 'Chennai',
    photos: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/c3/3c/97/gameistry.jpg?w=900&h=900&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/c2/fb/47/gameistry.jpg?w=1200&h=1200&s=1',
    ],
    rating: 4.7,
    reviews: [
      { id: 'r8', author: 'Sanjay V.', stars: 5, date: '2025-11-12', text: 'Over 1300 games — I\'ve never seen anything like it in Chennai. They have Twilight Imperium 4th Ed! The corporate event packages are superb.' },
      { id: 'r9', author: 'Ananya K.', stars: 5, date: '2025-10-28', text: 'Best board game venue in the city, full stop. The 4-hour weekday package at ₹299 is an absolute steal. Pristine copies of every game.' },
    ],
    pricePerHour: 119, perPerson: true,
    tables: [
      { id: 't4-1', label: 'Table 1', seats: 6 },
      { id: 't4-2', label: 'Table 2', seats: 8 },
      { id: 't4-3', label: 'Table 3', seats: 4 },
      { id: 't4-4', label: 'Table 4', seats: 6 },
      { id: 't4-5', label: 'Table 5', seats: 8 },
      { id: 't4-6', label: 'Table 6', seats: 6 },
    ],
    gameLibraryIds: ['g1', 'g2', 'g3', 'g4', 'g5', 'g6', 'g7', 'g8'],
    amenities: ['AC', 'Food & Drinks', 'Wi-Fi', 'Washrooms', 'Parking'],
    offer: { text: '4-hour weekday package at ₹299/person', window: 'Mon–Fri, all day' },
    distanceKm: 2.8, hours: '11 am – 10 pm', lat: 13.0732, lng: 80.2609,
  },
  {
    id: 'c5', name: 'Untangle – House of Puzzles', area: 'Teynampet', city: 'Chennai',
    photos: [
      'https://thesouthfirst.com/wp-content/uploads/2023/08/untangle-2.jpg',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/75/fe/ef/untangle-s-collection.jpg?w=700&h=400&s=1',
    ],
    rating: 4.6,
    reviews: [
      { id: 'r10', author: 'Nithya R.', stars: 5, date: '2025-11-16', text: '400+ board games and 1200+ puzzles under one roof! Family-friendly and the staff are great at recommending games for all skill levels.' },
      { id: 'r11', author: 'Aditya B.', stars: 5, date: '2025-10-20', text: '₹100 flat entry with unlimited game time is incredible value. Pandemic copy here is in perfect condition. My family\'s weekend spot.' },
    ],
    pricePerHour: 100, perPerson: true,
    tables: [
      { id: 't5-1', label: 'Table 1', seats: 4 },
      { id: 't5-2', label: 'Table 2', seats: 4 },
      { id: 't5-3', label: 'Table 3', seats: 6 },
      { id: 't5-4', label: 'Table 4', seats: 8 },
    ],
    gameLibraryIds: ['g1', 'g2', 'g3', 'g4', 'g5', 'g6', 'g8'],
    amenities: ['AC', 'Food & Drinks', 'Washrooms'],
    offer: { text: 'Flat ₹100 entry + ₹100 each additional hour', window: 'Tue–Sun, 11 am – 10 pm' },
    distanceKm: 2.5, hours: '11 am – 10 pm (Tue–Sun, closed Mon)', lat: 13.0418, lng: 80.2509,
  },
  {
    id: 'c6', name: 'Gamesync', area: 'Velachery', city: 'Chennai',
    photos: [
      'https://thesouthfirst.com/wp-content/uploads/2023/08/Gamesync-1.jpg',
    ],
    rating: 4.3,
    reviews: [
      { id: 'r12', author: 'Meenakshi S.', stars: 4, date: '2025-11-16', text: 'Cosy third-floor spot in Velachery. Staff are super helpful and genuinely love board games. Unlimited games package is great value.' },
      { id: 'r13', author: 'Rahul T.', stars: 5, date: '2025-10-20', text: '₹99 entry and you can play anything all day. Discovered Wingspan here and now I\'m obsessed. Will definitely be back every weekend.' },
    ],
    pricePerHour: 99, perPerson: true,
    tables: [
      { id: 't6-1', label: 'Table 1', seats: 6 },
      { id: 't6-2', label: 'Table 2', seats: 4 },
      { id: 't6-3', label: 'Table 3', seats: 6 },
    ],
    gameLibraryIds: ['g1', 'g2', 'g3', 'g5', 'g6', 'g8'],
    amenities: ['AC', 'Food & Drinks', 'Washrooms'],
    offer: { text: 'Unlimited games ₹299 weekdays, ₹399 weekends', window: 'Wed–Sun, 10 am – 10 pm' },
    distanceKm: 12.4, hours: '10 am – 10 pm (Wed–Sun)', lat: 12.9785, lng: 80.2209,
  },
];

export const CAFE_MAP: Record<string, Cafe> = Object.fromEntries(CAFES.map(c => [c.id, c]));

// ---- Users ----
const makeUser = (
  id: string, name: string, handle: string, avatar: string,
  isSuperHost: boolean, followers: number, following: number,
  showedUp: number, joined: number,
  meeples: MeepleAward[] = [],
): User => ({
  id, name, handle, avatarUrl: avatar, isSuperHost,
  followers, following,
  reliability: { percent: Math.round(showedUp / joined * 100), showedUp, joined },
  preferredDifficulties: ['medium'],
  preferredVibes: ['casual', 'social'],
  topGameIds: ['g2', 'g1'],
  meeples,
});

export const CURRENT_USER: User = {
  id: 'u0',
  name: 'Vishnu D.',
  handle: '@vishnud',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200',
  isSuperHost: true,
  followers: 142,
  following: 89,
  reliability: { percent: 94, showedUp: 31, joined: 33 },
  preferredDifficulties: ['medium', 'heavy'],
  preferredVibes: ['competitive', 'social'],
  topGameIds: ['g2', 'g6', 'g3'],
  bio: 'Strategy gamer based in Chennai. Love heavy euros and hidden-role games. Always down for a Wingspan session.',
  meeples: [
    { id: 'ma1', awardKey: 'tablemaster', title: 'The Tablemaster', subtext: 'Voted the standout of the whole meetup.', type: 'voted', gameId: 'g2', cafeName: 'Dice & Dine', meetupId: 'm1', votes: 4, dateWon: '2025-10-15' },
    { id: 'ma2', awardKey: 'mastermind', title: 'The Mastermind', subtext: 'For the sharpest tactical play at the table.', type: 'voted', gameId: 'g6', cafeName: 'Roll & Brew', meetupId: 'm3', votes: 3, dateWon: '2025-10-28' },
    { id: 'ma3', awardKey: 'grand-architect', title: 'The Grand Architect', subtext: "Built the slow-burn engine no one saw coming.", type: 'voted', gameId: 'g6', cafeName: 'Roll & Brew', meetupId: 'm3', votes: 3, dateWon: '2025-10-28' },
    { id: 'ma4', awardKey: 'ever-present', title: 'Ever-Present', subtext: 'Shows up, every single time. 95%+ reliability.', type: 'computed', earnedCriteria: '94% reliability across 33 meetups', dateWon: '2025-11-01' },
    { id: 'ma5', awardKey: 'convener', title: 'The Convener', subtext: 'A born host — ran 10+ meetups for the community.', type: 'computed', earnedCriteria: 'Hosted 12 meetups', dateWon: '2025-09-20' },
    { id: 'ma6', awardKey: 'marathoner', title: 'The Marathoner', subtext: 'Went the full distance on a 3-hour epic.', type: 'computed', earnedCriteria: 'Completed Twilight Imperium (6h) at Strategy Station', dateWon: '2025-08-30' },
    { id: 'ma7', awardKey: 'grace-under-fire', title: 'Grace Under Fire', subtext: 'Lost without sulking, won without gloating.', type: 'voted', gameId: 'g2', cafeName: 'The Meeple Lounge', meetupId: 'm5', votes: 4, dateWon: '2025-09-05' },
    { id: 'ma8', awardKey: 'closer', title: 'The Closer', subtext: 'Dead last, then sealed it on the final turn.', type: 'voted', gameId: 'g2', cafeName: 'Dice & Dine', meetupId: 'm1', votes: 2, dateWon: '2025-10-15' },
    { id: 'ma9', awardKey: 'heart-of-the-table', title: 'Heart of the Table', subtext: 'The one everyone wanted to keep playing with.', type: 'voted', gameId: 'g4', cafeName: 'Pawn & Brew', meetupId: 'm8', votes: 3, dateWon: '2025-07-12' },
    { id: 'ma10', awardKey: 'polymath', title: 'The Polymath', subtext: 'Took the crown across Light, Medium and Heavy games alike.', type: 'computed', earnedCriteria: 'Won awards in Light, Medium and Heavy meetups', dateWon: '2025-11-10' },
    { id: 'ma11', awardKey: 'city-explorer', title: 'City Explorer', subtext: 'Rolled dice at 10 different cafes across Chennai.', type: 'computed', earnedCriteria: 'Played at 10 distinct cafes', dateWon: '2025-10-01' },
    { id: 'ma12', awardKey: 'giant-slayer', title: 'The Giant Slayer', subtext: "Toppled the table's reigning champion.", type: 'voted', gameId: 'g6', cafeName: 'Pawn & Brew', meetupId: 'm9', votes: 3, dateWon: '2025-11-05' },
    { id: 'ma13', awardKey: 'comeback-kid', title: 'The Comeback Kid', subtext: 'Written off early, came roaring back to the front.', type: 'voted', gameId: 'g3', cafeName: 'Strategy Station', meetupId: 'm6', votes: 4, dateWon: '2025-08-18' },
    { id: 'ma14', awardKey: 'master-of-deception', title: 'Master of Deception', subtext: "Lied through their teeth and got away with all of it.", type: 'voted', gameId: 'g1', cafeName: 'Roll & Brew', meetupId: 'm2', votes: 5, dateWon: '2025-09-22' },
  ],
};

export const USERS: User[] = [
  CURRENT_USER,
  makeUser('u1', 'Priya S.', '@priyas', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200', true, 230, 110, 28, 30),
  makeUser('u2', 'Arjun K.', '@arjunk', 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200', false, 45, 62, 10, 13),
  makeUser('u3', 'Meera T.', '@meerat', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200', false, 78, 55, 18, 20),
  makeUser('u4', 'Karthik R.', '@karthikr', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200', false, 32, 40, 6, 9),
  makeUser('u5', 'Deepa V.', '@deepav', 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=200', false, 12, 28, 2, 4),
];

export const USER_MAP: Record<string, User> = Object.fromEntries(USERS.map(u => [u.id, u]));

// ---- Meetups ----
export const MEETUPS: Meetup[] = [
  {
    id: 'm1',
    host: USERS[1],
    cafe: CAFES[0],
    tableId: 't1-3',
    gameIds: ['g2'],
    date: 'Today',
    slots: [{ startTime: '7:00 pm', endTime: '8:00 pm' }, { startTime: '8:00 pm', endTime: '9:00 pm' }],
    estimatedTotalMin: 110,
    seatsFilled: 3, seatsTotal: 5,
    depositAmount: 150,
    cancelCutoffHours: 2,
    vibes: ['casual', 'social'],
    beginnersWelcome: true,
    note: 'Bringing the Cities & Knights expansion!',
    status: 'open',
    roster: [
      { userId: 'u1', status: 'confirmed', depositPaid: 150, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u2', status: 'confirmed', depositPaid: 150, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u3', status: 'confirmed', depositPaid: 150, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm2',
    host: USERS[2],
    cafe: CAFES[2],
    tableId: 't3-1',
    gameIds: ['g1', 'g8'],
    date: 'Today',
    slots: [{ startTime: '6:00 pm', endTime: '7:00 pm' }],
    estimatedTotalMin: 55,
    seatsFilled: 5, seatsTotal: 5,
    depositAmount: 100,
    cancelCutoffHours: 2,
    vibes: ['social', 'casual'],
    beginnersWelcome: true,
    status: 'full',
    roster: [
      { userId: 'u2', status: 'confirmed', depositPaid: 100, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u3', status: 'confirmed', depositPaid: 100, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u4', status: 'confirmed', depositPaid: 100, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u5', status: 'confirmed', depositPaid: 100, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u0', status: 'confirmed', depositPaid: 100, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm3',
    host: CURRENT_USER,
    cafe: CAFES[2],
    tableId: 't3-3',
    gameIds: ['g6'],
    date: '2025-12-20',
    slots: [
      { startTime: '2:00 pm', endTime: '3:00 pm' },
      { startTime: '3:00 pm', endTime: '4:00 pm' },
    ],
    estimatedTotalMin: 165,
    seatsFilled: 2, seatsTotal: 6,
    depositAmount: 200,
    cancelCutoffHours: 2,
    vibes: ['competitive', 'marathon'],
    beginnersWelcome: false,
    note: 'Only for players who have played at least once before.',
    status: 'open',
    roster: [
      { userId: 'u0', status: 'confirmed', depositPaid: 200, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u1', status: 'confirmed', depositPaid: 200, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm4',
    host: USERS[3],
    cafe: CAFES[1],
    tableId: 't2-3',
    gameIds: ['g3'],
    date: 'Today',
    slots: [{ startTime: '5:00 pm', endTime: '6:00 pm' }, { startTime: '6:00 pm', endTime: '7:00 pm' }],
    estimatedTotalMin: 90,
    seatsFilled: 4, seatsTotal: 5,
    depositAmount: 120,
    cancelCutoffHours: 2,
    vibes: ['casual'],
    beginnersWelcome: true,
    status: 'open',
    roster: [
      { userId: 'u4', status: 'confirmed', depositPaid: 120, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u1', status: 'confirmed', depositPaid: 120, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u2', status: 'confirmed', depositPaid: 120, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u5', status: 'confirmed', depositPaid: 120, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm5',
    host: USERS[1],
    cafe: CAFES[1],
    tableId: 't2-1',
    gameIds: ['g4'],
    date: '2025-12-21',
    slots: [{ startTime: '3:00 pm', endTime: '4:00 pm' }, { startTime: '4:00 pm', endTime: '5:00 pm' }],
    estimatedTotalMin: 75,
    seatsFilled: 1, seatsTotal: 4,
    depositAmount: 150,
    cancelCutoffHours: 2,
    vibes: ['competitive', 'social'],
    beginnersWelcome: false,
    status: 'open',
    roster: [
      { userId: 'u1', status: 'confirmed', depositPaid: 150, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm6',
    host: CURRENT_USER,
    cafe: CAFES[5],
    tableId: 't6-2',
    gameIds: ['g3'],
    date: '2025-08-18',
    slots: [{ startTime: '2:00 pm', endTime: '3:00 pm' }, { startTime: '3:00 pm', endTime: '4:00 pm' }],
    estimatedTotalMin: 90,
    seatsFilled: 5, seatsTotal: 5,
    depositAmount: 160,
    cancelCutoffHours: 2,
    vibes: ['casual', 'social'],
    beginnersWelcome: true,
    status: 'completed',
    roster: [
      { userId: 'u0', status: 'showed', depositPaid: 160, depositCredited: 160, forfeitedToCafe: 0 },
      { userId: 'u1', status: 'showed', depositPaid: 160, depositCredited: 160, forfeitedToCafe: 0 },
      { userId: 'u2', status: 'noShow', depositPaid: 160, depositCredited: 0, forfeitedToCafe: 160 },
      { userId: 'u3', status: 'showed', depositPaid: 160, depositCredited: 160, forfeitedToCafe: 0 },
      { userId: 'u4', status: 'showed', depositPaid: 160, depositCredited: 160, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm7',
    host: USERS[3],
    cafe: CAFES[3],
    tableId: 't4-2',
    gameIds: ['g7'],
    date: '2025-12-22',
    slots: [
      { startTime: '11:00 am', endTime: '12:00 pm' },
      { startTime: '12:00 pm', endTime: '1:00 pm' },
      { startTime: '1:00 pm', endTime: '2:00 pm' },
      { startTime: '2:00 pm', endTime: '3:00 pm' },
      { startTime: '3:00 pm', endTime: '4:00 pm' },
      { startTime: '4:00 pm', endTime: '5:00 pm' },
    ],
    estimatedTotalMin: 420,
    seatsFilled: 4, seatsTotal: 6,
    depositAmount: 250,
    cancelCutoffHours: 2,
    vibes: ['marathon', 'competitive'],
    beginnersWelcome: false,
    note: 'Full TI4 run. Pack snacks. We start at 11am sharp.',
    status: 'open',
    roster: [
      { userId: 'u4', status: 'confirmed', depositPaid: 250, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u0', status: 'confirmed', depositPaid: 250, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u1', status: 'confirmed', depositPaid: 250, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u2', status: 'confirmed', depositPaid: 250, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm8',
    host: USERS[2],
    cafe: CAFES[3],
    tableId: 't4-1',
    gameIds: ['g4'],
    date: '2025-07-12',
    slots: [{ startTime: '4:00 pm', endTime: '5:00 pm' }, { startTime: '5:00 pm', endTime: '6:00 pm' }],
    estimatedTotalMin: 75,
    seatsFilled: 4, seatsTotal: 4,
    depositAmount: 180,
    cancelCutoffHours: 2,
    vibes: ['casual', 'social'],
    beginnersWelcome: true,
    status: 'completed',
    roster: [
      { userId: 'u2', status: 'showed', depositPaid: 180, depositCredited: 180, forfeitedToCafe: 0 },
      { userId: 'u0', status: 'showed', depositPaid: 180, depositCredited: 180, forfeitedToCafe: 0 },
      { userId: 'u3', status: 'showed', depositPaid: 180, depositCredited: 180, forfeitedToCafe: 0 },
      { userId: 'u5', status: 'noShow', depositPaid: 180, depositCredited: 0, forfeitedToCafe: 180 },
    ],
  },
  {
    id: 'm9',
    host: USERS[1],
    cafe: CAFES[3],
    tableId: 't4-1',
    gameIds: ['g6'],
    date: '2025-11-05',
    slots: [{ startTime: '6:00 pm', endTime: '7:00 pm' }, { startTime: '7:00 pm', endTime: '8:00 pm' }, { startTime: '8:00 pm', endTime: '9:00 pm' }],
    estimatedTotalMin: 165,
    seatsFilled: 4, seatsTotal: 4,
    depositAmount: 200,
    cancelCutoffHours: 2,
    vibes: ['competitive'],
    beginnersWelcome: false,
    status: 'completed',
    roster: [
      { userId: 'u1', status: 'showed', depositPaid: 200, depositCredited: 200, forfeitedToCafe: 0 },
      { userId: 'u0', status: 'showed', depositPaid: 200, depositCredited: 200, forfeitedToCafe: 0 },
      { userId: 'u3', status: 'showed', depositPaid: 200, depositCredited: 200, forfeitedToCafe: 0 },
      { userId: 'u4', status: 'cancelledEarly', depositPaid: 200, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
  {
    id: 'm10',
    host: CURRENT_USER,
    cafe: CAFES[0],
    tableId: 't1-2',
    gameIds: ['g5', 'g1'],
    date: 'Today',
    slots: [{ startTime: '8:00 pm', endTime: '9:00 pm' }, { startTime: '9:00 pm', endTime: '10:00 pm' }],
    estimatedTotalMin: 95,
    seatsFilled: 2, seatsTotal: 4,
    depositAmount: 150,
    cancelCutoffHours: 2,
    vibes: ['casual', 'social'],
    beginnersWelcome: true,
    note: 'Starting with Ticket to Ride then Codenames — perfect family-friendly combo!',
    status: 'open',
    roster: [
      { userId: 'u0', status: 'confirmed', depositPaid: 150, depositCredited: 0, forfeitedToCafe: 0 },
      { userId: 'u5', status: 'confirmed', depositPaid: 150, depositCredited: 0, forfeitedToCafe: 0 },
    ],
  },
];

export const MEETUP_MAP: Record<string, Meetup> = Object.fromEntries(MEETUPS.map(m => [m.id, m]));

// ---- Bills ----
export const BILLS: Bill[] = [
  {
    meetupId: 'm6',
    lineItems: [
      { label: 'Table time (2 hrs)', amount: 640 },
      { label: 'Food & Drinks', amount: 800 },
    ],
    total: 1440,
    splits: [
      { userId: 'u0', share: 360, depositCredit: 160, amountDue: 200 },
      { userId: 'u1', share: 360, depositCredit: 160, amountDue: 200 },
      { userId: 'u3', share: 360, depositCredit: 160, amountDue: 200 },
      { userId: 'u4', share: 360, depositCredit: 160, amountDue: 200 },
    ],
  },
  {
    meetupId: 'm8',
    lineItems: [
      { label: 'Table time (2 hrs)', amount: 720 },
      { label: 'Food & Drinks', amount: 600 },
    ],
    total: 1320,
    splits: [
      { userId: 'u2', share: 440, depositCredit: 180, amountDue: 260 },
      { userId: 'u0', share: 440, depositCredit: 180, amountDue: 260 },
      { userId: 'u3', share: 440, depositCredit: 180, amountDue: 260 },
    ],
  },
  {
    meetupId: 'm9',
    lineItems: [
      { label: 'Table time (3 hrs)', amount: 1080 },
      { label: 'Food & Drinks', amount: 900 },
    ],
    total: 1980,
    splits: [
      { userId: 'u1', share: 660, depositCredit: 200, amountDue: 460 },
      { userId: 'u0', share: 660, depositCredit: 200, amountDue: 460 },
      { userId: 'u3', share: 660, depositCredit: 200, amountDue: 460 },
    ],
  },
];

// ---- Tournaments ----
export const TOURNAMENTS: Tournament[] = [
  {
    id: 'tr1', name: 'Chennai Catan Championship', gameId: 'g2',
    cafe: CAFES[0],
    startDate: '2025-12-28',
    teamsRegistered: 14, teamsTotal: 16,
    entryFee: 500, prizePool: 5000,
  },
  {
    id: 'tr2', name: 'Codenames City Cup', gameId: 'g1',
    cafe: CAFES[2],
    startDate: '2026-01-10',
    teamsRegistered: 8, teamsTotal: 12,
    entryFee: 300, prizePool: 3000,
  },
  {
    id: 'tr3', name: 'Heavy Games Grand Prix', gameId: 'g6',
    cafe: CAFES[5],
    startDate: '2026-01-18',
    teamsRegistered: 6, teamsTotal: 8,
    entryFee: 800, prizePool: 10000,
  },
];

// ---- Chats ----
export const CHATS: Chat[] = [
  {
    id: 'ch1', type: 'group', meetupId: 'm1',
    name: 'Catan @ Dice & Dine',
    participants: ['u0', 'u1', 'u2', 'u3'],
    messages: [
      { id: 'msg1', senderId: 'u1', text: 'Hey everyone! Super excited for tonight 🎲', timestamp: '2025-11-22T18:30:00' },
      { id: 'msg2', senderId: 'u2', text: "I'll be there by 7pm sharp", timestamp: '2025-11-22T18:45:00' },
      { id: 'msg3', senderId: 'u0', text: "Bringing the Cities & Knights expansion!", timestamp: '2025-11-22T19:00:00' },
      { id: 'msg4', senderId: 'u3', text: "Can't wait! First time playing with the expansion", timestamp: '2025-11-22T19:05:00' },
    ],
    lastMessage: "Can't wait! First time playing with the expansion",
    lastTimestamp: '2025-11-22T19:05:00',
    unreadCount: 2,
  },
  {
    id: 'ch2', type: 'direct',
    name: 'Priya S.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    participants: ['u0', 'u1'],
    messages: [
      { id: 'msg5', senderId: 'u1', text: 'Hey! Want to co-host a heavy game session next weekend?', timestamp: '2025-11-21T14:20:00' },
      { id: 'msg6', senderId: 'u0', text: "Absolutely! Brass or TI4?", timestamp: '2025-11-21T14:35:00' },
      { id: 'msg7', senderId: 'u1', text: "Let's do Brass first, TI4 is an all-day commitment 😅", timestamp: '2025-11-21T14:40:00' },
    ],
    lastMessage: "Let's do Brass first, TI4 is an all-day commitment 😅",
    lastTimestamp: '2025-11-21T14:40:00',
    unreadCount: 1,
  },
  {
    id: 'ch3', type: 'group', meetupId: 'm10',
    name: 'TTR + Codenames @ Dice & Dine',
    participants: ['u0', 'u5'],
    messages: [
      { id: 'msg8', senderId: 'u0', text: 'Meetup created! Join us tonight at 8pm 🚂', timestamp: '2025-11-22T10:00:00' },
      { id: 'msg9', senderId: 'u5', text: 'Joining! Love Ticket to Ride', timestamp: '2025-11-22T10:30:00' },
    ],
    lastMessage: 'Joining! Love Ticket to Ride',
    lastTimestamp: '2025-11-22T10:30:00',
    unreadCount: 0,
  },
  {
    id: 'ch4', type: 'direct',
    name: 'Arjun K.',
    avatarUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200',
    participants: ['u0', 'u2'],
    messages: [
      { id: 'msg10', senderId: 'u2', text: 'Bro that Brass game was insane. You shut me out of every coal mine!', timestamp: '2025-11-20T21:00:00' },
      { id: 'msg11', senderId: 'u0', text: 'Haha sorry not sorry 😂 Rematch?', timestamp: '2025-11-20T21:05:00' },
    ],
    lastMessage: 'Haha sorry not sorry 😂 Rematch?',
    lastTimestamp: '2025-11-20T21:05:00',
    unreadCount: 0,
  },
];
